package com.carhub.user;

import com.carhub.user.dto.UserResponse;
import org.mapstruct.Mapper;

/**
 * Maps the {@link User} document to its safe {@link UserResponse} projection.
 * Implementation is generated by MapStruct at compile time (Spring component model).
 */
@Mapper
public interface UserMapper {

    UserResponse toResponse(User user);
}
